micronaut:
  application:
    name: nossaCasaDoCodigo
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/aula
    driverClassName: org.postgresql.Driver
    username: postgres
    password: senha
    dialect: POSTGRES
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
      show:
        sql: true